const COUNTRY_OPTIONS = [
  { code: 'AF', name: 'Afghanistan' },
  { code: 'AX', name: 'Aland Islands' },
  { code: 'AL', name: 'Albania' },
  { code: 'DZ', name: 'Algeria' },
  { code: 'AS', name: 'American Samoa' },
  { code: 'AD', name: 'Andorra' },
  { code: 'AO', name: 'Angola' },
  { code: 'AI', name: 'Anguilla' },
  { code: 'AG', name: 'Antigua & Barbuda' },
  { code: 'AR', name: 'Argentina' },
  { code: 'AM', name: 'Armenia' },
  { code: 'AW', name: 'Aruba' },
  { code: 'AU', name: 'Australia' },
  { code: 'AT', name: 'Austria' },
  { code: 'AZ', name: 'Azerbaijan' },
  { code: 'BS', name: 'Bahamas' },
  { code: 'BH', name: 'Bahrain' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'BB', name: 'Barbados' },
  { code: 'BY', name: 'Belarus' },
  { code: 'BE', name: 'Belgium' },
  { code: 'BZ', name: 'Belize' },
  { code: 'BJ', name: 'Benin' },
  { code: 'BM', name: 'Bermuda' },
  { code: 'BT', name: 'Bhutan' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba' },
  { code: 'BA', name: 'Bosnia & Herzegovina' },
  { code: 'BW', name: 'Botswana' },
  { code: 'BR', name: 'Brazil' },
  { code: 'IO', name: 'British Indian Ocean Territory' },
  { code: 'VG', name: 'British Virgin Islands' },
  { code: 'BN', name: 'Brunei' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi' },
  { code: 'CV', name: 'Cabo Verde' },
  { code: 'KH', name: 'Cambodia' },
  { code: 'CM', name: 'Cameroon' },
  { code: 'CA', name: 'Canada' },
  { code: 'KY', name: 'Cayman Islands' },
  { code: 'CF', name: 'Central African Republic' },
  { code: 'TD', name: 'Chad' },
  { code: 'CL', name: 'Chile' },
  { code: 'CN', name: 'China' },
  { code: 'CX', name: 'Christmas Island' },
  { code: 'CC', name: 'Cocos (Keeling) Islands' },
  { code: 'CO', name: 'Colombia' },
  { code: 'KM', name: 'Comoros' },
  { code: 'CG', name: 'Congo' },
  { code: 'CD', name: 'Congo (DRC)' },
  { code: 'CK', name: 'Cook Islands' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'CI', name: "Cote d'Ivoire" },
  { code: 'HR', name: 'Croatia' },
  { code: 'CU', name: 'Cuba' },
  { code: 'CW', name: 'Curacao' },
  { code: 'CY', name: 'Cyprus' },
  { code: 'CZ', name: 'Czechia' },
  { code: 'DK', name: 'Denmark' },
  { code: 'DJ', name: 'Djibouti' },
  { code: 'DM', name: 'Dominica' },
  { code: 'DO', name: 'Dominican Republic' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'EG', name: 'Egypt' },
  { code: 'SV', name: 'El Salvador' },
  { code: 'GQ', name: 'Equatorial Guinea' },
  { code: 'ER', name: 'Eritrea' },
  { code: 'EE', name: 'Estonia' },
  { code: 'SZ', name: 'Eswatini' },
  { code: 'ET', name: 'Ethiopia' },
  { code: 'FK', name: 'Falkland Islands' },
  { code: 'FO', name: 'Faroe Islands' },
  { code: 'FJ', name: 'Fiji' },
  { code: 'FI', name: 'Finland' },
  { code: 'FR', name: 'France' },
  { code: 'GF', name: 'French Guiana' },
  { code: 'PF', name: 'French Polynesia' },
  { code: 'GA', name: 'Gabon' },
  { code: 'GM', name: 'Gambia' },
  { code: 'GE', name: 'Georgia' },
  { code: 'DE', name: 'Germany' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GI', name: 'Gibraltar' },
  { code: 'GR', name: 'Greece' },
  { code: 'GL', name: 'Greenland' },
  { code: 'GD', name: 'Grenada' },
  { code: 'GP', name: 'Guadeloupe' },
  { code: 'GU', name: 'Guam' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'GG', name: 'Guernsey' },
  { code: 'GN', name: 'Guinea' },
  { code: 'GW', name: 'Guinea-Bissau' },
  { code: 'GY', name: 'Guyana' },
  { code: 'HT', name: 'Haiti' },
  { code: 'HN', name: 'Honduras' },
  { code: 'HK', name: 'Hong Kong SAR' },
  { code: 'HU', name: 'Hungary' },
  { code: 'IS', name: 'Iceland' },
  { code: 'IN', name: 'India' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'IR', name: 'Iran' },
  { code: 'IQ', name: 'Iraq' },
  { code: 'IE', name: 'Ireland' },
  { code: 'IM', name: 'Isle of Man' },
  { code: 'IL', name: 'Israel' },
  { code: 'IT', name: 'Italy' },
  { code: 'JM', name: 'Jamaica' },
  { code: 'JP', name: 'Japan' },
  { code: 'JE', name: 'Jersey' },
  { code: 'JO', name: 'Jordan' },
  { code: 'KZ', name: 'Kazakhstan' },
  { code: 'KE', name: 'Kenya' },
  { code: 'KI', name: 'Kiribati' },
  { code: 'KR', name: 'Korea' },
  { code: 'XK', name: 'Kosovo' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'KG', name: 'Kyrgyzstan' },
  { code: 'LA', name: 'Laos' },
  { code: 'LV', name: 'Latvia' },
  { code: 'LB', name: 'Lebanon' },
  { code: 'LS', name: 'Lesotho' },
  { code: 'LR', name: 'Liberia' },
  { code: 'LY', name: 'Libya' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LT', name: 'Lithuania' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'MO', name: 'Macao SAR' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MW', name: 'Malawi' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'MV', name: 'Maldives' },
  { code: 'ML', name: 'Mali' },
  { code: 'MT', name: 'Malta' },
  { code: 'MH', name: 'Marshall Islands' },
  { code: 'MQ', name: 'Martinique' },
  { code: 'MR', name: 'Mauritania' },
  { code: 'MU', name: 'Mauritius' },
  { code: 'YT', name: 'Mayotte' },
  { code: 'MX', name: 'Mexico' },
  { code: 'FM', name: 'Micronesia' },
  { code: 'MD', name: 'Moldova' },
  { code: 'MC', name: 'Monaco' },
  { code: 'MN', name: 'Mongolia' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'MS', name: 'Montserrat' },
  { code: 'MA', name: 'Morocco' },
  { code: 'MZ', name: 'Mozambique' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'NA', name: 'Namibia' },
  { code: 'NR', name: 'Nauru' },
  { code: 'NP', name: 'Nepal' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'NC', name: 'New Caledonia' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'NI', name: 'Nicaragua' },
  { code: 'NE', name: 'Niger' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'NU', name: 'Niue' },
  { code: 'NF', name: 'Norfolk Island' },
  { code: 'KP', name: 'North Korea' },
  { code: 'MK', name: 'North Macedonia' },
  { code: 'MP', name: 'Northern Mariana Islands' },
  { code: 'NO', name: 'Norway' },
  { code: 'OM', name: 'Oman' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'PW', name: 'Palau' },
  { code: 'PS', name: 'Palestinian Authority' },
  { code: 'PA', name: 'Panama' },
  { code: 'PG', name: 'Papua New Guinea' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'PE', name: 'Peru' },
  { code: 'PH', name: 'Philippines' },
  { code: 'PN', name: 'Pitcairn Islands' },
  { code: 'PL', name: 'Poland' },
  { code: 'PT', name: 'Portugal' },
  { code: 'PR', name: 'Puerto Rico' },
  { code: 'QA', name: 'Qatar' },
  { code: 'RE', name: 'Reunion' },
  { code: 'RO', name: 'Romania' },
  { code: 'RU', name: 'Russia' },
  { code: 'RW', name: 'Rwanda' },
  { code: 'WS', name: 'Samoa' },
  { code: 'SM', name: 'San Marino' },
  { code: 'ST', name: 'Sao Tome & Principe' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'SN', name: 'Senegal' },
  { code: 'RS', name: 'Serbia' },
  { code: 'SC', name: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone' },
  { code: 'SG', name: 'Singapore' },
  { code: 'SX', name: 'Sint Maarten' },
  { code: 'SK', name: 'Slovakia' },
  { code: 'SI', name: 'Slovenia' },
  { code: 'SB', name: 'Solomon Islands' },
  { code: 'SO', name: 'Somalia' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'SS', name: 'South Sudan' },
  { code: 'ES', name: 'Spain' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'SH', name: 'St Helena, Ascension, Tristan da Cunha' },
  { code: 'BL', name: 'St. Barthelemy' },
  { code: 'KN', name: 'St. Kitts & Nevis' },
  { code: 'LC', name: 'St. Lucia' },
  { code: 'MF', name: 'St. Martin' },
  { code: 'PM', name: 'St. Pierre & Miquelon' },
  { code: 'VC', name: 'St. Vincent & Grenadines' },
  { code: 'SD', name: 'Sudan' },
  { code: 'SR', name: 'Suriname' },
  { code: 'SJ', name: 'Svalbard & Jan Mayen' },
  { code: 'SE', name: 'Sweden' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'SY', name: 'Syria' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'TJ', name: 'Tajikistan' },
  { code: 'TZ', name: 'Tanzania' },
  { code: 'TH', name: 'Thailand' },
  { code: 'TL', name: 'Timor-Leste' },
  { code: 'TG', name: 'Togo' },
  { code: 'TK', name: 'Tokelau' },
  { code: 'TO', name: 'Tonga' },
  { code: 'TT', name: 'Trinidad & Tobago' },
  { code: 'TN', name: 'Tunisia' },
  { code: 'TR', name: 'Turkiye' },
  { code: 'TM', name: 'Turkmenistan' },
  { code: 'TC', name: 'Turks & Caicos Islands' },
  { code: 'TV', name: 'Tuvalu' },
  { code: 'UM', name: 'U.S. Outlying Islands' },
  { code: 'VI', name: 'U.S. Virgin Islands' },
  { code: 'UG', name: 'Uganda' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'US', name: 'United States' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'UZ', name: 'Uzbekistan' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'VA', name: 'Vatican City' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'WF', name: 'Wallis & Futuna' },
  { code: 'YE', name: 'Yemen' },
  { code: 'ZM', name: 'Zambia' },
  { code: 'ZW', name: 'Zimbabwe' },
];

const COUNTRY_NATIVE_LOCALES = {
  AF: 'fa-AF',
  AX: 'sv-AX',
  AL: 'sq-AL',
  DZ: 'ar-DZ',
  AS: 'sm-AS',
  AD: 'ca-AD',
  AO: 'pt-AO',
  AR: 'es-AR',
  AM: 'hy-AM',
  AT: 'de-AT',
  AZ: 'az-AZ',
  BH: 'ar-BH',
  BD: 'bn-BD',
  BY: 'be-BY',
  BE: 'nl-BE',
  BJ: 'fr-BJ',
  BT: 'dz-BT',
  BO: 'es-BO',
  BQ: 'nl-BQ',
  BA: 'bs-BA',
  BR: 'pt-BR',
  BN: 'ms-BN',
  BG: 'bg-BG',
  BF: 'fr-BF',
  BI: 'rn-BI',
  CV: 'pt-CV',
  KH: 'km-KH',
  CM: 'fr-CM',
  CF: 'fr-CF',
  TD: 'fr-TD',
  CL: 'es-CL',
  CN: 'zh-CN',
  CO: 'es-CO',
  KM: 'ar-KM',
  CG: 'fr-CG',
  CD: 'fr-CD',
  CR: 'es-CR',
  CI: 'fr-CI',
  HR: 'hr-HR',
  CU: 'es-CU',
  CW: 'nl-CW',
  CY: 'el-CY',
  CZ: 'cs-CZ',
  DK: 'da-DK',
  DJ: 'fr-DJ',
  DO: 'es-DO',
  EC: 'es-EC',
  EG: 'ar-EG',
  SV: 'es-SV',
  GQ: 'es-GQ',
  ER: 'ti-ER',
  EE: 'et-EE',
  SZ: 'ss-SZ',
  ET: 'am-ET',
  FO: 'fo-FO',
  FJ: 'fj-FJ',
  FI: 'fi-FI',
  FR: 'fr-FR',
  GF: 'fr-GF',
  PF: 'fr-PF',
  GA: 'fr-GA',
  GM: 'ff-GM',
  GE: 'ka-GE',
  DE: 'de-DE',
  GR: 'el-GR',
  GL: 'kl-GL',
  GP: 'fr-GP',
  GT: 'es-GT',
  GN: 'fr-GN',
  GW: 'pt-GW',
  HT: 'ht-HT',
  HN: 'es-HN',
  HK: 'zh-HK',
  HU: 'hu-HU',
  IS: 'is-IS',
  IN: 'hi-IN',
  ID: 'id-ID',
  IR: 'fa-IR',
  IQ: 'ar-IQ',
  IL: 'he-IL',
  IT: 'it-IT',
  JP: 'ja-JP',
  JO: 'ar-JO',
  KZ: 'kk-KZ',
  KE: 'sw-KE',
  KR: 'ko-KR',
  XK: 'sq-XK',
  KW: 'ar-KW',
  KG: 'ky-KG',
  LA: 'lo-LA',
  LV: 'lv-LV',
  LB: 'ar-LB',
  LS: 'st-LS',
  LY: 'ar-LY',
  LI: 'de-LI',
  LT: 'lt-LT',
  LU: 'lb-LU',
  MO: 'zh-MO',
  MG: 'mg-MG',
  MW: 'ny-MW',
  MY: 'ms-MY',
  MV: 'dv-MV',
  ML: 'fr-ML',
  MT: 'mt-MT',
  MQ: 'fr-MQ',
  MR: 'ar-MR',
  MU: 'mfe-MU',
  YT: 'fr-YT',
  MX: 'es-MX',
  MD: 'ro-MD',
  MC: 'fr-MC',
  MN: 'mn-MN',
  ME: 'sr-ME',
  MA: 'ar-MA',
  MZ: 'pt-MZ',
  MM: 'my-MM',
  NA: 'af-NA',
  NP: 'ne-NP',
  NL: 'nl-NL',
  NC: 'fr-NC',
  NI: 'es-NI',
  NE: 'fr-NE',
  KP: 'ko-KP',
  MK: 'mk-MK',
  NO: 'nb-NO',
  OM: 'ar-OM',
  PK: 'ur-PK',
  PS: 'ar-PS',
  PA: 'es-PA',
  PY: 'es-PY',
  PE: 'es-PE',
  PH: 'fil-PH',
  PL: 'pl-PL',
  PT: 'pt-PT',
  PR: 'es-PR',
  QA: 'ar-QA',
  RE: 'fr-RE',
  RO: 'ro-RO',
  RU: 'ru-RU',
  RW: 'rw-RW',
  SM: 'it-SM',
  ST: 'pt-ST',
  SA: 'ar-SA',
  SN: 'fr-SN',
  RS: 'sr-RS',
  SC: 'fr-SC',
  SL: 'kr-SL',
  SX: 'nl-SX',
  SK: 'sk-SK',
  SI: 'sl-SI',
  SO: 'so-SO',
  ZA: 'zu-ZA',
  SS: 'ar-SS',
  ES: 'es-ES',
  LK: 'si-LK',
  BL: 'fr-BL',
  MF: 'fr-MF',
  PM: 'fr-PM',
  SD: 'ar-SD',
  SR: 'nl-SR',
  SJ: 'nb-SJ',
  SE: 'sv-SE',
  CH: 'de-CH',
  SY: 'ar-SY',
  TW: 'zh-TW',
  TJ: 'tg-TJ',
  TZ: 'sw-TZ',
  TH: 'th-TH',
  TL: 'pt-TL',
  TG: 'fr-TG',
  TN: 'ar-TN',
  TR: 'tr-TR',
  TM: 'tk-TM',
  UA: 'uk-UA',
  AE: 'ar-AE',
  UY: 'es-UY',
  UZ: 'uz-UZ',
  VA: 'it-VA',
  VE: 'es-VE',
  VN: 'vi-VN',
  WF: 'fr-WF',
  YE: 'ar-YE',
};

function getNativeCountryName(country) {
  const locale = COUNTRY_NATIVE_LOCALES[country.code];

  if (!locale || typeof Intl === 'undefined' || typeof Intl.DisplayNames !== 'function') {
    return country.name;
  }

  try {
    return new Intl.DisplayNames([locale], { type: 'region' }).of(country.code) ?? country.name;
  } catch {
    return country.name;
  }
}

export const COUNTRIES = COUNTRY_OPTIONS.map((country) => {
  const nativeName = getNativeCountryName(country);
  return {
    ...country,
    englishName: country.name,
    name: nativeName,
  };
});

export function findCountryByCode(code) {
  if (!code) {
    return null;
  }

  return COUNTRIES.find((country) => country.code === code) ?? null;
}
