export const UI = {
  colors: {
    background: '#fff8fb',
    surface: '#ffffff',
    surfaceMuted: '#fff3f7',
    border: '#f3d0dd',
    borderSoft: '#f7dbe5',
    text: '#20131a',
    textMuted: '#7a5968',
    textSoft: '#8d6676',
    primary: '#e52b50',
    success: '#2c8c54',
    danger: '#d72647',
    overlay: 'rgba(32, 19, 26, 0.34)',
  },
  radius: {
    card: 20,
    row: 16,
    button: 14,
    modal: 22,
  },
  spacing: {
    screen: 18,
    section: 22,
    card: 16,
    gap: 12,
    modal: 20,
  },
  modal: {
    maxWidth: 360,
    titleSize: 20,
    bodySize: 15,
    bodyLineHeight: 22,
    buttonMinHeight: 48,
    overlayPadding: 24,
  },
  auth: {
    screenPaddingBottom: 36,
    horizontalPadding: 28,
    titleSize: 36,
    titleSpacing: 32,
    fieldGap: 16,
    inputMinHeight: 54,
    inputRadius: 16,
    buttonMinHeight: 54,
    pillMinHeight: 40,
    linkGap: 20,
    secondaryLinkGap: 14,
  },
  empty: {
    iconGap: 8,
    titleSize: 24,
    textSize: 15,
    horizontalPadding: 24,
  },
  header: {
    eyebrowGap: 8,
    titleSize: 30,
    titleGap: 10,
    hintSize: 16,
    hintLineHeight: 23,
    sectionGap: 18,
  },
  browseCard: {
    minHeight: 96,
    badgeSize: 52,
    badgeRadius: 26,
    badgeGap: 16,
    titleSize: 19,
    metaSize: 14,
  },
};
